version: '3.8'
services:
  backend:
    build:
      context: 'backend'
      dockerfile: 'Dockerfile.dev'
    container_name: 'backend'
    volumes:
      - './backend:/app'
      - '/app/node_modules/'
      - './.git:/app/.git'
    ports:
      - 4000:4000
    tty: true
    stdin_open: false
